name: our_app
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.11
  - pip
# Dependencies that will be installed via PyPi
  - pip:
      - httplib2>=0.9.0
      - configparser>=3.5.0
      - dicttoxml==1.7.16
      - gunicorn==21.2.0
      - flask-restx==1.1.0
      - Flask==2.3.2
      - Jinja2==3.1.2
      - Werkzeug==2.3.7
      - MarkupSafe==2.1.3
      - flask-cors==4.0.0
      - flask_httpauth==4.8.0
      - flask_limiter==3.5.1